= Custom static content resolve

This is a "Hello world" project. It aims to show how to customize Spring MVC to serve static content depending on user locale.

== What's in there ?

 - A Spring Boot/MVC project based on Gradle/java 11 generated by https://start.spring.io[Spring starter].
 - Static content is served from files in resources: `src/main/resources/static/{lang}/...'
 - Configuration to customize static content location is done in class `StaticContentConfiguration`

== Requirements

A command line to execute compilation/run scripts

== Compile/run

Run `./gradlew bootRun` or `./gradlew.bat bootRun` if you're a windows user

== Test it

The project starts a web server on `localhost:8080`that can serve a single endpoint `hello.txt` in english or french language.

*Note*: Truth is there's a second endpoint, but you'll find it quickly.

=== Curl

Run the following command by setting your language header:

 - French: `curl -H "Accept-Language: fr" http://localhost:8080/hello.txt`
 - English: `curl -H "Accept-Language: en" http://localhost:8080/hello.txt`

== Browser:

Use the `lang` query parameter to customize language. So either go to http://localhost:8080/hello.txt?lang=fr or to http://localhost:8080/hello.txt?lang=en